### PR TITLE
Make mocks test code

### PR DESCRIPTION
**Pull request by cldmstr**
The generated mock classes were being created as part of the application code and not part of the test code. Added `_test` to the mock files so that they are no longer included with the real code.

### CODE REVIEW

**Review by cloudlena — CHANGES_REQUESTED** [review]
Nice find, @cldmstr!

When running `go generate ./...`, for me, all generated files change. Are you maybe not using the latest `moq@v0.2.7`?

**Comment by cldmstr** [comment]
I'm having trouble with moq anyway. I do have the newest version installed, but the reason you get a lot of changes is, that when generating the `replicaset` interface moq, the generation creates uncompilable code for me. It has two import aliases that are the same. For some reason, this didn't happen in the earlier version, or was already manually fixed.

**Comment by cldmstr** [comment]
Created issue on the `matryer/moq` repository to fix the import issues: https://github.com/matryer/moq/issues/184

**Comment by cldmstr** [comment]
> Thanks, @cldmstr. Should we then merge this PR here?

I think we can. I just pushed an update that I made with my fork of the `matryer/moq` tool and that also got rid of the whitespace changes that you had mentioned.

**Review by cloudlena — APPROVED** [review]

**Pull request merged**
